// Mock data for development

import { Zap, Shield, TrendingUp } from 'lucide-react'

export const mockMatches = [
  {
    id: 1,
    homeTeam: 'Manchester City',
    awayTeam: 'Liverpool',
    homeTeamLogo: '/teams/man-city.png',
    awayTeamLogo: '/teams/liverpool.png',
    homeWinProb: 58,
    drawProb: 22,
    awayWinProb: 20,
    kickoffTime: '3:00 PM',
    confidence: 'high' as const,
    competitionName: 'Premier League',
    expectedGoalsHome: 2.1,
    expectedGoalsAway: 1.3,
  },
  {
    id: 2,
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    homeTeamLogo: '/teams/real-madrid.png',
    awayTeamLogo: '/teams/barcelona.png',
    homeWinProb: 45,
    drawProb: 28,
    awayWinProb: 27,
    kickoffTime: '8:45 PM',
    confidence: 'medium' as const,
    competitionName: 'La Liga',
    expectedGoalsHome: 1.8,
    expectedGoalsAway: 1.6,
  },
  {
    id: 3,
    homeTeam: 'Bayern Munich',
    awayTeam: 'Borussia Dortmund',
    homeTeamLogo: '/teams/bayern.png',
    awayTeamLogo: '/teams/dortmund.png',
    homeWinProb: 62,
    drawProb: 19,
    awayWinProb: 19,
    kickoffTime: '5:30 PM',
    confidence: 'high' as const,
    competitionName: 'Bundesliga',
    expectedGoalsHome: 2.3,
    expectedGoalsAway: 1.1,
  },
  {
    id: 4,
    homeTeam: 'PSG',
    awayTeam: 'Marseille',
    homeTeamLogo: '/teams/psg.png',
    awayTeamLogo: '/teams/marseille.png',
    homeWinProb: 71,
    drawProb: 16,
    awayWinProb: 13,
    kickoffTime: '7:00 PM',
    confidence: 'high' as const,
    competitionName: 'Ligue 1',
    expectedGoalsHome: 2.5,
    expectedGoalsAway: 0.9,
  },
  {
    id: 5,
    homeTeam: 'Newcastle',
    awayTeam: 'Brighton',
    homeTeamLogo: '/teams/newcastle.png',
    awayTeamLogo: '/teams/brighton.png',
    homeWinProb: 48,
    drawProb: 27,
    awayWinProb: 25,
    kickoffTime: '12:30 PM',
    confidence: 'low' as const,
    competitionName: 'Premier League',
    expectedGoalsHome: 1.2,
    expectedGoalsAway: 1.4,
  },
]

export const mockScenarios = [
  {
    id: 1,
    title: 'Goals & Chances',
    description: '3+ goals in the match',
    probability: 65,
    color: 'cyan' as const,
    icon: Zap,
  },
  {
    id: 2,
    title: 'Defensive Battle',
    description: 'Under 1.5 goals',
    probability: 35,
    color: 'purple' as const,
    icon: Shield,
  },
  {
    id: 3,
    title: 'Home Win',
    description: 'Strong performance',
    probability: 58,
    color: 'orange' as const,
    icon: TrendingUp,
  },
]

export const mockGamificationData = {
  level: 8,
  currentXP: 2450,
  nextLevelXP: 5000,
  totalXP: 42500,
  streak: 5,
  predictions: 47,
  accuracy: 68,
  badges: [
    { id: 1, name: 'Perfect Week', icon: '⭐', achieved: true },
    { id: 2, name: 'Hot Streak', icon: '🔥', achieved: true },
    { id: 3, name: 'Early Bird', icon: '🌅', achieved: false },
    { id: 4, name: 'Prediction Master', icon: '🎯', achieved: true },
  ],
}

export const mockLeaderboard = [
  {
    id: 1,
    rank: 1,
    username: 'PredictionKing',
    level: 12,
    xp: 85000,
    accuracy: 74,
    predictions: 156,
    avatar: '👑',
  },
  {
    id: 2,
    rank: 2,
    username: 'StatsWizard',
    level: 11,
    xp: 72000,
    accuracy: 72,
    predictions: 142,
    avatar: '🧙',
  },
  {
    id: 3,
    rank: 3,
    username: 'GoalHunter',
    level: 10,
    xp: 61000,
    accuracy: 70,
    predictions: 128,
    avatar: '⚽',
  },
  {
    id: 4,
    rank: 4,
    username: 'YourUsername',
    level: 8,
    xp: 42500,
    accuracy: 68,
    predictions: 47,
    avatar: '⚡',
  },
]

export const mockLiveMatches = [
  {
    id: 1,
    homeTeam: 'Chelsea',
    awayTeam: 'Manchester United',
    homeScore: 1,
    awayScore: 0,
    minute: 34,
    status: 'LIVE',
    homeWinProb: 65,
  },
  {
    id: 2,
    homeTeam: 'Arsenal',
    awayTeam: 'Tottenham',
    homeScore: 2,
    awayScore: 1,
    minute: 71,
    status: 'LIVE',
    homeWinProb: 72,
  },
]

export const mockInsights = [
  'Manchester City has been on a 5-game winning streak with an average of 2.8 goals per game.',
  'Liverpool\'s defense has conceded only 3 shots on target in the last 4 matches.',
  'The Over 2.5 Goals has hit in 7 of the last 8 meetings between these teams.',
  'Expected Goals analysis shows City\'s attack is 15% above average this season.',
]

export default {
  mockMatches,
  mockScenarios,
  mockGamificationData,
  mockLeaderboard,
  mockLiveMatches,
  mockInsights,
}
